### ISSUE TITLE
No error message is shown after a declined payment

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#4] opened 2017-01-04 11:42 UTC
During a checkout, when the payment is declined for some reason, the user is redirected to the shipping page, but no error message is shown to the user. You can reproduce this problem using the credit card number 4180000000000566 (it will be rejected).

**Comment by lsv** [comment] 2017-01-04 13:26
Is the error messages in body response?
Header > ErrorMessage ?

**Comment by ghost** [comment] 2017-01-04 13:45
Yes, the URL `<magento backend>/sdmaltapay/index/fail` will be called by the gateway.

The gateway will send, for example:

```
<?xml version="1.0"?>
<APIResponse version="20160719">
    <Header>
        <Date>2017-01-04T14:42:12+01:00</Date>
        <Path>API/reservationOfFixedAmount</Path>
        <ErrorCode>0</ErrorCode>
        <ErrorMessage/>
    </Header>
    <Body>
        <Result>Failed</Result>
        <MerchantErrorMessage>TestAcquirer[amount=5.66 case]</MerchantErrorMessage>
        <CardHolderErrorMessage>Card Declined</CardHolderErrorMessage>
        <CardHolderMessageMustBeShown>false</CardHolderMessageMustBeShown>
        <Transactions>
            <Transaction>
```

**Comment by lsv** [comment] 2017-01-04 13:50
Which key do you want me to write in a message? just CardHolderErrorMessage ?

**Comment by ghost** [comment] 2017-01-04 14:14
Yes, exactly.

**Comment by ghost** [comment] 2017-04-03 11:40
The error message is still not being shown for the customer.

**Comment by lb-altapay-com** [comment] 2017-09-29 14:10
This was test with Magento 2.1.7, 2.1.8 and 2.1.9 . The issue is still present.

**Comment by sz-altapay-com** [comment] 2018-02-14 15:16
This issue has been fixed in version 0.1.9.

**Closed as completed by sz-altapay-com** 2018-02-14 15:16 UTC
